### ISSUE TITLE
ReBuild checklist

### ISSUE THREAD

**Issue by JFixby** [picfight/pfcd#1]
- [x] Block Time: 1min 
- [x] Network Min Difficulty
- [x] Genesis block start difficulty
- [x] Organizational PkScript (Dev Address)
- [x] Agendas
- [x] Subsidy
- [x] DNS
- [x] Premine 
- [x] Ticket pool size
